
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author thepr
 */
public class frmLogin extends javax.swing.JPanel {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
    }
    
    public static void main(String[] args) {
        JFrame frame = new JFrame("frmLogin Demo");
        frmLogin panel = new frmLogin();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add(panel);
        frame.pack();
        frame.setVisible(true);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jblUsuario = new javax.swing.JLabel();
        txtUsuario = new java.awt.TextField();
        jblContrasena = new javax.swing.JLabel();
        txtContrasena = new java.awt.TextField();
        btnRegresar = new javax.swing.JButton();
        btnIniciarSesion = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        jLabel1.setText("Iniciar Sesión");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 160, 40));

        jblUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jblUsuario.setText("Usuario:");
        jPanel1.add(jblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 200, 30));

        jblContrasena.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jblContrasena.setText("Contraseña:");
        jPanel1.add(jblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));
        jPanel1.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 200, 30));

        btnRegresar.setText("Regresar");
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 160, 40));

        btnIniciarSesion.setText("Iniciar sesión");
        jPanel1.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jblContrasena;
    private javax.swing.JLabel jblUsuario;
    private java.awt.TextField txtContrasena;
    private java.awt.TextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
